db-uri = "@/run/credentials/stockinsider-postgrest.service/database-uri"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "@/run/credentials/stockinsider-postgrest.service/jwt-secret"
server-host = "127.0.0.1"
server-port = 3301
db-pool = 10
db-pool-acquisition-timeout = 10
db-extra-search-path = "public"
openapi-mode = "disabled"
