import test from 'node:test';
import assert from 'node:assert/strict';
import {validateResearchDeepClaimContext,type ResearchDeepClaimContextV2}from './research-deep-claim-context.ts';
import {validateResearchDeepAuthorInput,parseAuthorInputRequest}from './research-deep-author-input.ts';
import {buildPrivateDeepDraft}from './research-deep-draft.ts';
import {researchCanonicalHash as hash}from './research-agent-qualification.ts';
const owner='synthetic-observed-owner', now='2026-10-08T01:01:00.000001Z';
function fixture(){
 const context:ResearchDeepClaimContextV2={schemaVersion:'research-deep-claim-context-v2',observedAt:now,job:{jobId:'11111111-1111-4111-8111-111111111111',symbol:'5347',priorityRunId:'22222222-2222-4222-8222-222222222222',attempt:1,owner,leaseExpiresAt:'2026-10-08T01:30:00Z'},modelReservation:{reservationId:'33333333-3333-4333-8333-333333333333',role:'company_research',owner,workKey:'deep:11111111-1111-4111-8111-111111111111:1',startedAt:'2026-10-08T01:00:00Z',leaseExpiresAt:'2026-10-08T01:30:00Z'},modelCompletion:null,researchIdentity:{scope:'research_observed_v1',researchCompanyId:'44444444-4444-4444-8444-444444444444',snapshotHash:'a'.repeat(64),mappingDigest:'b'.repeat(64),stockId:null,priorityInputHash:'c'.repeat(64),snapshotReceivedAt:'2026-10-08T00:00:00Z',snapshotObservedAt:'2026-10-07T23:00:00Z',priorityAsOf:'2026-10-08T00:30:00Z'}};
 const material={schemaVersion:'research-deep-author-input-v2',researchIdentity:context.researchIdentity,dataCutoff:now,discovery:{runId:context.job.priorityRunId,asOf:context.researchIdentity.priorityAsOf,inputHash:context.researchIdentity.priorityInputHash},job:context.job,modelReservation:context.modelReservation,financial:null,sources:[],gaps:[{reason:'dossier_not_selected'}],requiresIndependentReview:true,modelDispatched:false,authoritativePublication:false,sourceSelectionComplete:false,financialForecastComplete:false};
 return {context,packet:{...material,inputHash:hash(material)},expected:{owner,scope:'research_observed_v1' as const,snapshotHash:context.researchIdentity.snapshotHash,now}};
}
test('observed context is explicit, closed and cannot be downgraded to v1',()=>{
 const {context,expected}=fixture();assert.deepEqual(validateResearchDeepClaimContext(context,expected),context);
 assert.throws(()=>validateResearchDeepClaimContext(context,{owner,now}));
 const {researchIdentity,...base}=context;void researchIdentity;
 assert.throws(()=>validateResearchDeepClaimContext({...base,schemaVersion:'research-deep-claim-context-v1'},expected));
 for(const key of ['researchCompanyId','mappingDigest','snapshotHash']){const c=structuredClone(context);Object.assign(c.researchIdentity,{[key]:'invalid'});assert.throws(()=>validateResearchDeepClaimContext(c,expected));}
});
test('receipt future microsecond and scope hash mismatch reject',()=>{const {context,expected}=fixture();const c=structuredClone(context);c.researchIdentity.snapshotReceivedAt='2026-10-08T00:30:00.000001Z';assert.throws(()=>validateResearchDeepClaimContext(c,expected));assert.throws(()=>validateResearchDeepClaimContext(context,{...expected,snapshotHash:'d'.repeat(64)}));});
test('author input retains scoped hash and missing financial gap',()=>{const {context,packet}=fixture();assert.equal(validateResearchDeepAuthorInput(packet,context,now).schemaVersion,'research-deep-author-input-v2');const req={owner,scope:'research_observed_v1',snapshotHash:context.researchIdentity.snapshotHash,jobId:context.job.jobId,attempt:1,reservationId:context.modelReservation.reservationId,bundleId:null,sourceDocumentIds:[]};assert.equal(parseAuthorInputRequest(req).scope,'research_observed_v1');assert.throws(()=>parseAuthorInputRequest({...req,modelPriceContext:{}}));});
test('rehashed scope/mapping/discovery tampering cannot bind original context',()=>{const {context,packet}=fixture();for(const change of [(p:typeof packet)=>{p.researchIdentity.mappingDigest='d'.repeat(64);},(p:typeof packet)=>{p.discovery.inputHash='e'.repeat(64);},(p:typeof packet)=>{p.schemaVersion='research-deep-author-input-v1';}]){const p=structuredClone(packet);change(p);const {inputHash,...material}=p;void inputHash;p.inputHash=hash(material);assert.throws(()=>validateResearchDeepAuthorInput(p,context,now));}});
test('private incomplete v2 draft at19minutes preserves preparation time and original deadlines',()=>{
 const {context,packet}=fixture();const raw={schemaVersion:'research-deep-prepared-input-v2',sourceCommit:'1'.repeat(40),requestHash:'2'.repeat(64),originalRequestHash:'3'.repeat(64),packet,preparedAt:now,modelCalls:0,modelDispatched:false,authoritativePublication:false};const prepared={...raw,receiptHash:hash(raw)};
 const model={schemaVersion:'research-deep-model-draft-v2',preparedReceiptHash:prepared.receiptHash,inputHash:packet.inputHash,job:context.job,modelReservation:context.modelReservation,researchIdentity:context.researchIdentity,article:{schemaVersion:'candidate-deep-research-v1',symbol:'5347',authoredAt:'2026-10-08T01:19:00Z',evidenceCutoffAt:now,summary:'Synthetic incomplete draft only; not actual research or a model execution.',sections:[],catalysts:[],scenarios:[]}};
 const input={prepared,model,expectedPreparedHash:prepared.receiptHash,original:{originalRequestHash:raw.originalRequestHash,owner,observedAt:now,context},controllerSourceCommit:'1'.repeat(40),now:'2026-10-08T01:19:00Z'};
 const draft=buildPrivateDeepDraft(input);assert.equal(draft.schemaVersion,'research-deep-private-draft-v2');assert.equal(draft.handoff.schemaVersion,'research-deep-author-handoff-v2');assert.equal(draft.handoff.proposedRequest,null);assert.deepEqual(draft.researchIdentity,context.researchIdentity);assert.equal(draft.articleContractStatus,'incomplete');assert.equal(draft.dataCutoff,now);assert.equal(draft.job.leaseExpiresAt,context.job.leaseExpiresAt);
 const changed=structuredClone(model);changed.researchIdentity.mappingDigest='f'.repeat(64);assert.throws(()=>buildPrivateDeepDraft({...input,model:changed}));
});
