import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const sql=readFileSync(new URL('../migrations/20260909_official_financial_validation_receipts.sql',import.meta.url),'utf8');
test('official validation migration is additive, guarded, receipt-backed and PIT-stamped',()=>{
  assert.doesNotMatch(sql,/DROP TABLE|TRUNCATE|DELETE FROM/u);
  assert.match(sql,/ENABLE ROW LEVEL SECURITY/u);
  assert.match(sql,/FROM PUBLIC,anon,authenticated/u);
  assert.match(sql,/GRANT SELECT ON public[.]official_financial_validation_receipts TO service_role/u);
  assert.doesNotMatch(sql,/GRANT SELECT,INSERT ON public[.]official_financial_validation_receipts TO service_role/u);
  assert.match(sql,/GRANT EXECUTE[\s\S]*TO service_role/u);
  assert.match(sql,/WHERE fact_id=p_fact_id AND recorded_at=p_recorded_at/u);
  assert.match(sql,/source_sha256=p_source_sha256/u);
  assert.match(sql,/p_validator_principal,'opportunity_runner'::public[.]internal_principal_role_v3/u);
  assert.match(sql,/SET search_path=''/u);
  assert.match(sql,/official_validation_rpc_owner_provenance_select/u);
  assert.match(sql,/official_validation_rpc_owner_receipt_select/u);
  assert.match(sql,/official_validation_rpc_owner_receipt_update/u);
  assert.match(sql,/validator_version='official-financial-v2' AND r[.]validator_principal IS NOT NULL/u);
  assert.match(sql,/WHEN first_receipt[.]id IS NOT NULL THEN\s+'[{]"validation_status":"pending"/u);
  assert.doesNotMatch(sql,/first_receipt[.]prior_validation/u);
  assert.match(sql,/INSERT INTO public.official_financial_validation_receipts/u);
  assert.match(sql,/v_at := clock_timestamp\(\)/u);
  assert.match(sql,/validation_recorded_at=\(v_effective->>'validation_recorded_at'\)::timestamptz/u);
  assert.match(sql,/prior_validation,effective_validation/u);
  assert.match(sql,/r.validated_at<=p_cutoff/u);
  assert.match(sql,/FUNCTION public.read_financial_facts_as_of\(p_cutoff timestamptz\)/u);
  assert.match(sql,/v_prior->>'validation_status' IN \('rejected','conflict','stale'\)/u);
  assert.doesNotMatch(sql,/v_fact[.]validation_status IN \('rejected','conflict','stale'\)/u);
});
test('validation covers the full candidate universe independently of acquisition backlog',()=>{
  const research=readFileSync(new URL('../web/src/lib/candidate-research.ts',import.meta.url),'utf8');
  const worker=readFileSync(new URL('../web/src/lib/official-financial-validation-worker.ts',import.meta.url),'utf8');
  assert.match(research,/validatePendingOfficialFinancials\(proposedUniverse\.map/u);
  assert.doesNotMatch(worker,/Set\(stockIds\)\]\)\.slice|Set\(stockIds\)\]\.slice/u);
  assert.match(worker,/acceptedHashes\.has/u);
  assert.match(worker,/r[.]validator_version === 'official-financial-v2'/u);
  assert.match(worker,/typeof r[.]validator_principal === 'string'/u);
  assert.match(worker,/p_validator_principal: validatorPrincipal/u);
});
