import test from 'node:test';import assert from 'node:assert/strict';import {readFile}from 'node:fs/promises';
import {buildModel,loadInputs,forecast,assumptions,renderArticle}from '../docs/research/2026-10-08-emc-company-model/recompute.mjs';
import {conditionalEps}from '../docs/research/2026-10-08-auo-four-segment-model/recompute.mjs';
import {renderResearchTokens,researchTable}from './lib/research-model-article.mjs';
const {values}=await loadInputs(),cutoff='2026-10-08T12:12:00Z',m=buildModel(...values.slice(0,3),cutoff,...values.slice(3)),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6);
test('eight real quarters reconcile signed tax/NCI without inventing derived EPS',()=>{assert.equal(m.actualQuarters.length,8);for(const q of m.actualQuarters){const v=q.values;near(v.netProfit,v.ownersNetProfit+v.nonControllingNetProfit);if(q.method!=='reported_quarter')assert.equal(v.reportedDilutedEps,undefined);}assert.equal(m.reportedQ1BasicEps,14.9);assert.notEqual(42.46-27.55,m.reportedQ1BasicEps);});
test('monthly quarter differences remain unexplained and Q3 EPS absent',()=>{near(m.q3KnownMonthlyRevenue.sumMillion,60884.517);assert.equal(m.q3KnownMonthlyRevenue.q3EpsPublished,false);assert.equal(m.monthlyReconciliation.length,7);assert.equal(m.monthlyReconciliation[4].differenceMonthlyMinusFinancialTwd,-18573000);});
for(const s of m.scenarios)test(`${s.id} 6 profit bridges, signed NCI, annual and forward periods`,()=>{for(const q of s.quarters){near(q.operatingProfit,q.grossProfit-q.operatingExpenses);near(q.pretaxProfit,q.operatingProfit+q.nonOperating);near(q.netProfit,q.pretaxProfit-q.taxExpense);near(q.ownersNetProfit,q.netProfit-q.nonControllingNetProfit);near(q.dilutedEpsConditional,q.ownersNetProfit/q.dilutedSharesMillionAssumed);near(q.nonOperating,Object.values(q.interestBreakdown).reduce((x,y)=>x+y,0));assert.equal(q.commercialVolumeBridge,null);}near(s.calendar2026.ownersNetProfit,15213.191+s.quarters[0].ownersNetProfit+s.quarters[1].ownersNetProfit);assert.deepEqual(s.nextFourUnreported.periods,['2026Q3','2026Q4','2027Q1','2027Q2']);assert.equal(s.targetPrice,null);});
test('reported exact ordinary/potential shares and comparative numerator adjustments retained',()=>{assert.equal(m.shares.exactHistoricalWeightedSharesVerified,true);near(m.shares.ordinaryBaselineMillion,358.321);near(m.shares.reportedQ2DilutedMillion,358.417);near(m.shares.reportedH1DilutedMillion,358.497);assert.equal(m.shares.notes.convertibleAfterTaxNumeratorAdjustment[1],-30322);assert.equal(m.shares.futureSharesVerified,false);});
test('hypothetical loss excludes potential awards; negative NCI increases parent profit',()=>{const q=forecast('2027Q1',100,{...assumptions.bear,grossMargin:.01,opexRatio:.50},0,10);assert.ok(q.ownersNetProfit<0);near(q.dilutedSharesMillionAssumed,10);assert.ok(q.antiDilutiveExcludedMillion>0);near(q.ownersNetProfit,q.netProfit+1);assert.equal(conditionalEps(0,10,1).potentialIncludedMillion,0);});
test('bad units, duplicate/month gap and altered financial bridge fail',()=>{for(const mutation of [v=>v[0].amountUnit='TWD',v=>v[0].monthlyRevenue.unit='TWD_thousands',v=>v[0].monthlyRevenue.rows[0].month='2024-11',v=>v[0].quarters[0].values.tax+=1]){const copy=structuredClone(values);mutation(copy);assert.throws(()=>buildModel(...copy.slice(0,3),cutoff,...copy.slice(3)));}});
test('future nanos/reversed microseconds and future session fail',()=>{let c=structuredClone(values);c[2].recordedAt='2026-10-08T12:12:00.000000001Z';assert.throws(()=>buildModel(...c.slice(0,3),cutoff,...c.slice(3)));c=structuredClone(values);c[2].sources[0].attemptedAt='2026-10-08T10:08:54.327100Z';assert.throws(()=>buildModel(...c.slice(0,3),cutoff,...c.slice(3)));c=structuredClone(values);c[1].bars.at(-1).date='2026-10-09';assert.throws(()=>buildModel(...c.slice(0,3),cutoff,...c.slice(3)));});
test('physical capacity plan and broker history cannot enter revenue as confirmed orders',()=>{assert.equal(m.capacityPlan.capacityByYear['2027'],9.3);assert.equal(m.productEconomics.capacity,null);assert.ok(m.scenarios.every(s=>s.multipleCalibrated===false));assert.ok(m.reversePriceSensitivity.every(s=>s.calibrated===false));});
test('X0.00 remains named and unadjusted diagnostics cannot approve entry or total return',()=>{assert.equal(m.rawTechnicalDiagnostic.nonComparableDates[0].date,'2026-08-28');assert.equal(m.rawTechnicalDiagnostic.totalReturn,false);assert.equal(m.rawTechnicalDiagnostic.entryApproved,false);assert.equal(m.rawTechnicalDiagnostic.benchmarkRelativeReturn,null);assert.equal(m.rawTechnicalDiagnostic.values.close,6000);});
test('shared renderer checks rectangular tables and all required tokens',()=>{assert.throws(()=>researchTable(['a'],[[1,2]]));assert.throws(()=>renderResearchTokens('{{A}}',{}));assert.equal(renderResearchTokens('{{A}}', {A:'x'}),'x');});
test('same evidence/cutoff hash and article exactly rebuild; 4–6k original narrative cites direct links',async()=>{assert.equal(buildModel(...values.slice(0,3),cutoff,...values.slice(3)).canonicalHash,m.canonicalHash);const folder=new URL('../docs/research/2026-10-08-emc-company-model/',import.meta.url);const template=await readFile(new URL('article-template.md',folder),'utf8'),article=await readFile(new URL('article.md',folder),'utf8');assert.equal(renderArticle(m,template),article);const body=article.split('<details>')[0],count=[...body].filter(c=>c>='\u4e00'&&c<='\u9fff').length;assert.ok(count>=4000&&count<=6000,`main Han ${count}`);const refs=new Set([...article.matchAll(/^\[([A-Z]+)\]: https:\/\//gm)].map(r=>r[1]));for(const r of body.matchAll(/\[([A-Z]+)\]/g))assert.ok(refs.has(r[1]));assert.ok(article.includes('53.61'));assert.ok(article.includes('不是2026/10/8共識')||article.includes('不能稱為2026/10/8共識'));});

test('product revenues and interest/finance/FX reconcile without grade mix or double count',()=>{const p=m.reportedProductRevenue['2026Q2'];assert.equal(p.prepreg+p.copperCladLaminate+p.other,47275194);const n=m.reportedNonopNotes;assert.equal(n.bankInterestIncome[0]+n.otherGainsLossesTotal[0]-n.financeCost[0],51568);assert.equal(m.productEconomics.productMix,null);});
test('current187–226media expectations reverse to required revenue/margins, not adopted base',()=>{assert.deepEqual(m.currentExpectationReverse.map(r=>r.mediaAttributedEps),[187,226]);assert.equal(m.currentMediaExpectations.brokerOriginalRead,false);assert.ok(m.currentExpectationReverse[1].requiredRevenueAtBaseMargins>m.scenarios[1].calendar2027.revenue);assert.ok(m.media38GrossMarginSensitivity.epsAtBaseRevenue>m.scenarios[1].calendar2027.dilutedEpsConditional);});

test('2026 annual potential shares preserve reported H1 weight rather than adding rounded EPS',()=>{near(m.shares.annual2026HistoricalH1PotentialWeightMillion,.088);near(m.scenarios[1].calendar2026.dilutedSharesMillionAssumed,358.409);near(m.scenarios[1].nextFourUnreported.potentialWeightedSharesMillionAssumed,358.321*.005/2);});
