import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile,rename,rm,symlink} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createHash,randomUUID} from 'node:crypto';
import {performance} from 'node:perf_hooks';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {FinancialDeadline,readPinnedFinancialFiles,FINANCIAL_READ_LIMITS} from '../web/src/lib/research-financial-file-reader.ts';
import {parseFinancialSupplementRequest,loadResearchFinancialSupplement,assertFinancialJsonBytes} from '../web/src/lib/research-financial-supplement.ts';
import {financialInstant} from '../web/src/lib/research-financial-clock.ts';
import {financialInventory} from '../web/src/lib/research-financial-inventory.ts';
test('bundled fixed inventory exactly equals approved design bytes/paths/hashes',async()=>assert.deepEqual(financialInventory,JSON.parse(await readFile(new URL('../openspec/changes/research-first-publication-v2/financial-adapter-files.json',import.meta.url),'utf8'))));
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const hash=v=>createHash('sha256').update(typeof v==='string'||Buffer.isBuffer(v)?v:canonical(v)).digest('hex');
function canonical(v){if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;return JSON.stringify(v);}
const request=()=>({request:{owner:'synthetic-financial-author',jobId:randomUUID(),attempt:1,reservationId:randomUUID(),bundleId:null,sourceDocumentIds:[],scope:'research_observed_v1',snapshotHash:'a'.repeat(64)},preparationId:randomUUID(),preparationInputHash:''});
function dbFixture(symbol,options={}){const input=request(),payload={symbol,scope:input.request.scope,snapshotHash:input.request.snapshotHash,modelDispatched:false};input.preparationInputHash=hash(payload);const saved={preparation_id:input.preparationId,input_hash:input.preparationInputHash,payload,request:input.request,replay:true,dispatchReady:false,job_id:input.request.jobId,attempt:1,reservation_id:input.request.reservationId,admitted_at:new Date().toISOString()};let calls=0;return{input,saved,get calls(){return calls;},db:{rpc(name,args){assert.equal(name,'assert_research_input_preparation_v2');assert.deepEqual(args,{p_request:input.request,p_preparation_id:input.preparationId,p_input_hash:input.preparationInputHash});calls++;const response=options.response?.(calls,saved)??{data:structuredClone(saved),error:null};const p=options.stall?new Promise(()=>{}):Promise.resolve(response);p.abortSignal=()=>p;return p;}}};}
for(const[symbol,folder]of[['2409','auo-four-segment'],['2383','emc-company']])test(symbol+' actual immutable relay projection and independently recalculated bridges',async()=>{const f=dbFixture(symbol),before=JSON.stringify(f.saved);const result=await loadResearchFinancialSupplement(f.db,f.input,root);const old=JSON.parse(await readFile(root+'/docs/research/2026-10-08-'+folder+'-model/model-results.json','utf8'));assert.equal(f.calls,2);assert.equal(JSON.stringify(f.saved),before);assert.equal(result.financialVerified,false);assert.equal(result.dispatchReady,false);assert.equal(result.modelDispatched,false);assert.equal(result.projection.originalModelCanonicalHash,old.canonicalHash);assert.notEqual(result.projection.sourceManifestHash,old.canonicalHash);assert.ok(result.projection.reportedFacts.length>25&&result.projection.reportedFacts.length<=64);assert.ok(!JSON.stringify(result).includes('sourceNumericLines'));for(let s=0;s<3;s++)for(let q=0;q<6;q++)for(const metric of ['revenue','grossProfit','operatingExpenses','operatingProfit','nonOperating','pretaxProfit','taxExpense','netProfit','ownersNetProfit','dilutedEpsConditional'])assert.ok(Math.abs(result.calculation.scenarios[s].quarters[q][metric]-old.scenarios[s].quarters[q][metric])<1e-6,metric);assert.equal(result.calculation.scenarios[0].calendarActualPlusForecast.status,'incomplete');assert.ok(result.calculatorExecutionHash.length===64);if(symbol==='2409')assert.deepEqual(result.projection.allocationDiscrepancies.derivedMinusOriginal.operatingProfit,[363974,-546733,182759,0]);else assert.equal(result.projection.clocks.shareNotesRecordedAt,'2026-10-08T12:08:29.997535+00:00');});
test('actual EP8 company remains unsupported and does not read AUO files',async()=>{const f=dbFixture('5347');const r=await loadResearchFinancialSupplement(f.db,f.input,'/unavailable/server-root');assert.equal(r.status,'unavailable');assert.equal(r.reason,'fixed_company_calculator_not_available');assert.equal(f.calls,2);});
for(const[field,value]of [['command','never-run'],['calculatorId','../anything'],['path','/tmp'],['symbol','2383'],['financialVerified',true]])test('closed request rejects caller '+field,()=>{const f=dbFixture('2409');assert.throws(()=>parseFinancialSupplementRequest({...f.input.request,preparationId:f.input.preparationId,preparationInputHash:f.input.preparationInputHash,[field]:value}));});
for(const scenario of ['wrongHash','withdrawn','completedAfterRead','crossScope'])test('live original preparation recheck rejects '+scenario,async()=>{const f=dbFixture('2409',{response:(n,s)=>scenario==='withdrawn'||scenario==='completedAfterRead'&&n===2?{data:null,error:{message:'original_lease_lost'}}:{data:{...s,...(scenario==='wrongHash'?{input_hash:'b'.repeat(64)}:{}),payload:scenario==='crossScope'?{...s.payload,scope:'formal_v1'}:s.payload},error:null}});await assert.rejects(loadResearchFinancialSupplement(f.db,f.input,root));});
test('stalled lease dependency cannot produce a late success under shared10s deadline',{timeout:12000},async()=>{const f=dbFixture('2409',{stall:true});const start=performance.now();await assert.rejects(loadResearchFinancialSupplement(f.db,f.input,root),/financial_deadline/);assert.ok(performance.now()-start<11000);});
test('nanosecond ordering and invalid finite calendar retained',()=>{assert.ok(financialInstant('2026-10-08T10:00:00.000000001Z')<financialInstant('2026-10-08T10:00:00.000000002Z'));assert.throws(()=>financialInstant('2026-02-30T10:00:00Z'));});
async function fixture(contents=['1']){const parent=path.join(root,'.agent','financial-fd-tests-'+randomUUID());await mkdir(parent,{recursive:true,mode:0o700});await mkdir(parent+'/docs/research',{recursive:true,mode:0o700});const pins=[];for(let i=0;i<contents.length;i++){const raw=Buffer.from(contents[i]),file='docs/research/'+i+'.json';await writeFile(parent+'/'+file,raw,{mode:0o600});pins.push({path:file,bytes:raw.length,sha256:hash(raw)});}return{root:parent,pins,close:()=>rm(parent,{recursive:true,force:true})};}
test('actual read exact per-file/aggregate caps; +1 fails without truncate success',async()=>{const f=await fixture(['1'+' '.repeat(524287),'2'+' '.repeat(524287),'3']);try{const d=new FinancialDeadline(),files=await readPinnedFinancialFiles(f.root,f.pins.slice(0,2),d);assert.equal(files.records.size,2);await files.close();await assert.rejects(readPinnedFinancialFiles(f.root,f.pins,new FinancialDeadline()),/read_bound/);await assert.rejects(readPinnedFinancialFiles(f.root,[{...f.pins[0],bytes:524289}],new FinancialDeadline()),/pin_invalid/);}finally{await f.close();}});
for(const kind of ['fifo','directory','symlink','replaceBeforeOpen','replaceParent','shortRead','mutateAfterRead'])test('bounded regular FD rejects '+kind,async()=>{const f=await fixture();try{const filename=f.root+'/'+f.pins[0].path;let hook=()=>{};if(kind==='fifo'){await rm(filename);execFileSync('mkfifo',[filename]);}if(kind==='directory'){await rm(filename);await mkdir(filename);}if(kind==='symlink'){await rename(filename,filename+'.saved');await symlink(filename+'.saved',filename);}if(kind==='replaceBeforeOpen')hook=async name=>{if(name.startsWith('before_open')){await rename(filename,filename+'.saved');execFileSync('mkfifo',[filename]);}};if(kind==='replaceParent')hook=async name=>{if(name.startsWith('before_open')){await rename(path.dirname(filename),path.dirname(filename)+'.saved');await mkdir(path.dirname(filename));await writeFile(filename,'1');}};if(kind==='shortRead')hook=async name=>{if(name.startsWith('before_open'))await writeFile(filename,'');};if(kind==='mutateAfterRead')hook=async name=>{if(name.startsWith('after_read'))await writeFile(filename,'2');};const start=performance.now();await assert.rejects(readPinnedFinancialFiles(f.root,f.pins,new FinancialDeadline(),hook));assert.ok(performance.now()-start<1000);}finally{await f.close();}});
test('projection/result UTF8 exact and +1, not character count',()=>{for(const cap of[FINANCIAL_READ_LIMITS.projection,FINANCIAL_READ_LIMITS.result]){assert.doesNotThrow(()=>assertFinancialJsonBytes('x'.repeat(cap-2),cap));assert.throws(()=>assertFinancialJsonBytes('x'.repeat(cap-1),cap));assert.throws(()=>assertFinancialJsonBytes('界'.repeat(Math.ceil(cap/3)),cap));}});
test('late async success discarded by monotonic deadline',async()=>{const d=new FinancialDeadline();Object.defineProperty(d,'end',{value:performance.now()+15});await assert.rejects(d.wait(new Promise(r=>setTimeout(()=>r('late'),40))),/financial_deadline/);});
