import test from 'node:test';
import assert from 'node:assert/strict';
import {continueInsiderSnapshots,validateInsiderContinuationResponse} from './research-insider-continuation.mjs';
const runId='11111111-1111-4111-8111-111111111111';
const pins=Array.from({length:5},(_,dataset)=>({dataset,snapshotId:`00000000-0000-4000-8000-00000000000${dataset}`}));
function response(round=1){const members=pins.map(p=>({...p,offset:p.dataset===0?Math.min(round*500,1001):0,totalRows:p.dataset===0?1001:0,generation:p.dataset===0?round:1,complete:p.dataset===0?round===3:true,observedAt:'2026-10-07T00:00:01Z',attemptedAt:'2026-10-07T00:00:00Z',hash:'a'.repeat(64)}));const complete=round===3;return {status:complete?200:502,body:{ok:complete,result:{connector:'twse_insider',errorCode:null,degradedReason:complete?null:'insider_bounded_response_pages_remaining',terminalReason:complete?'success':'partial',metadata:{insider_snapshot:{schema:'insider_snapshot_progress_v1',runId,pins,members,remainingRows:1001-members[0].offset,outcome:complete?'coverage_complete':'pages_remaining'}}}}};}
test('only typed exact pinned502 pages continue, durable journal precedes all calls',async()=>{const journals=[];let calls=0;const result=await continueInsiderSnapshots({runId},{invoke:async(body)=>{assert.ok(journals.length>calls);assert.equal(body.connector,'twse_insider');if(calls)assert.deepEqual(body.insiderSnapshot.pins,pins);return response(++calls);},saveJournal:async v=>journals.push(structuredClone(v))});assert.equal(calls,3);assert.equal(result.stopped,'complete');assert.equal(journals[0].request.runId,runId);assert.equal(journals[1].progress.members[1].complete,true);});
for(const mutate of [r=>r.body=null,r=>r.status=500,r=>r.body.result.errorCode='mixed_failure',r=>r.body.result.degradedReason='other',r=>r.body.result.metadata.insider_snapshot.pins[0].snapshotId=runId,r=>r.body.result.metadata.insider_snapshot.members[0].offset=999])test(`unknown502/pins/mixed/progress rejection stops with zero retry ${String(mutate)}`,async()=>{let calls=0;await assert.rejects(continueInsiderSnapshots({runId,pins},{invoke:async()=>{calls++;const r=structuredClone(response());mutate(r);return r;},saveJournal:async()=>{}}));assert.equal(calls,1);});
test('lost HTTP response never retries, save failure prevents next page',async()=>{let calls=0;await assert.rejects(continueInsiderSnapshots({runId},{invoke:async()=>{calls++;throw Error('lost');},saveJournal:async()=>{}}),/lost/);assert.equal(calls,1);calls=0;await assert.rejects(continueInsiderSnapshots({runId},{invoke:async()=>{calls++;return response();},saveJournal:async value=>{if(value.invocations)throw Error('disk');}}),/disk/);assert.equal(calls,1);});
test('bounded invocation/deadline stop retains complete pins for explicit resume',async()=>{let clock=0;let calls=0;const result=await continueInsiderSnapshots({runId},{invoke:async()=>{calls++;clock=1800001;return response();},saveJournal:async()=>{},monotonicNow:()=>clock});assert.equal(calls,1);assert.equal(result.stopped,'bounded_stop');assert.deepEqual(result.request.pins,pins);assert.equal(result.progress.members[1].complete,true);const next=await continueInsiderSnapshots(result.request,{previous:result.progress,maxInvocations:1,invoke:async()=>response(2),saveJournal:async()=>{}});assert.equal(next.invocations,1);assert.equal(next.progress.members[0].offset,1000);});
test('completed member drift and source clock renewal reject',()=>{const previous=validateInsiderContinuationResponse(response(),{runId}).progress;for(const change of [r=>r.body.result.metadata.insider_snapshot.members[1].complete=false,r=>r.body.result.metadata.insider_snapshot.members[0].observedAt='2026-10-08T00:00:01Z']){const r=structuredClone(response(2));change(r);assert.throws(()=>validateInsiderContinuationResponse(r,{runId,pins},previous));}});
